/*
СМС шлюз от Eskiz.uz

Отправляйте СМС по всему миру, в любом количестве!  В тестовом статусе для отправки тестовых смс сообщений, Вы можете использовать только нижеуказанные тексты:  - Это тест от Eskiz      - Bu Eskiz dan test      - This is test from Eskiz

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eskizapi

import (
	"encoding/json"
)

// checks if the Recommendation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Recommendation{}

// Recommendation struct for Recommendation
type Recommendation struct {
	From *string `form:"from" json:"from,omitempty"`
	To   *string `form:"to" json:"to,omitempty"`
}

// NewRecommendation instantiates a new Recommendation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecommendation() *Recommendation {
	this := Recommendation{}
	return &this
}

// NewRecommendationWithDefaults instantiates a new Recommendation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecommendationWithDefaults() *Recommendation {
	this := Recommendation{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *Recommendation) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Recommendation) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *Recommendation) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *Recommendation) SetFrom(v string) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *Recommendation) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Recommendation) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *Recommendation) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *Recommendation) SetTo(v string) {
	o.To = &v
}

func (o Recommendation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Recommendation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableRecommendation struct {
	value *Recommendation
	isSet bool
}

func (v NullableRecommendation) Get() *Recommendation {
	return v.value
}

func (v *NullableRecommendation) Set(val *Recommendation) {
	v.value = val
	v.isSet = true
}

func (v NullableRecommendation) IsSet() bool {
	return v.isSet
}

func (v *NullableRecommendation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecommendation(val *Recommendation) *NullableRecommendation {
	return &NullableRecommendation{value: val, isSet: true}
}

func (v NullableRecommendation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecommendation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
