/*
СМС шлюз от Eskiz.uz

Отправляйте СМС по всему миру, в любом количестве!  В тестовом статусе для отправки тестовых смс сообщений, Вы можете использовать только нижеуказанные тексты:  - Это тест от Eskiz      - Bu Eskiz dan test      - This is test from Eskiz

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eskizapi

import (
	"encoding/json"
)

// checks if the UserMessagesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserMessagesResponse{}

// UserMessagesResponse struct for UserMessagesResponse
type UserMessagesResponse struct {
	Data   *PaginationData `form:"data" json:"data,omitempty"`
	Status *string         `form:"status" json:"status,omitempty"`
}

// NewUserMessagesResponse instantiates a new UserMessagesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserMessagesResponse() *UserMessagesResponse {
	this := UserMessagesResponse{}
	return &this
}

// NewUserMessagesResponseWithDefaults instantiates a new UserMessagesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserMessagesResponseWithDefaults() *UserMessagesResponse {
	this := UserMessagesResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UserMessagesResponse) GetData() PaginationData {
	if o == nil || IsNil(o.Data) {
		var ret PaginationData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserMessagesResponse) GetDataOk() (*PaginationData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UserMessagesResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given PaginationData and assigns it to the Data field.
func (o *UserMessagesResponse) SetData(v PaginationData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UserMessagesResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserMessagesResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UserMessagesResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *UserMessagesResponse) SetStatus(v string) {
	o.Status = &v
}

func (o UserMessagesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserMessagesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableUserMessagesResponse struct {
	value *UserMessagesResponse
	isSet bool
}

func (v NullableUserMessagesResponse) Get() *UserMessagesResponse {
	return v.value
}

func (v *NullableUserMessagesResponse) Set(val *UserMessagesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserMessagesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserMessagesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserMessagesResponse(val *UserMessagesResponse) *NullableUserMessagesResponse {
	return &NullableUserMessagesResponse{value: val, isSet: true}
}

func (v NullableUserMessagesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserMessagesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
