/*
СМС шлюз от Eskiz.uz

Отправляйте СМС по всему миру, в любом количестве!  В тестовом статусе для отправки тестовых смс сообщений, Вы можете использовать только нижеуказанные тексты:  - Это тест от Eskiz      - Bu Eskiz dan test      - This is test from Eskiz

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eskizapi

import (
	"encoding/json"
)

// checks if the TotalByMonthResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TotalByMonthResponse{}

// TotalByMonthResponse struct for TotalByMonthResponse
type TotalByMonthResponse struct {
	Data []MonthlyReportItem `form:"data" json:"data,omitempty"`
}

// NewTotalByMonthResponse instantiates a new TotalByMonthResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTotalByMonthResponse() *TotalByMonthResponse {
	this := TotalByMonthResponse{}
	return &this
}

// NewTotalByMonthResponseWithDefaults instantiates a new TotalByMonthResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTotalByMonthResponseWithDefaults() *TotalByMonthResponse {
	this := TotalByMonthResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *TotalByMonthResponse) GetData() []MonthlyReportItem {
	if o == nil || IsNil(o.Data) {
		var ret []MonthlyReportItem
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TotalByMonthResponse) GetDataOk() ([]MonthlyReportItem, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TotalByMonthResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []MonthlyReportItem and assigns it to the Data field.
func (o *TotalByMonthResponse) SetData(v []MonthlyReportItem) {
	o.Data = v
}

func (o TotalByMonthResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TotalByMonthResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableTotalByMonthResponse struct {
	value *TotalByMonthResponse
	isSet bool
}

func (v NullableTotalByMonthResponse) Get() *TotalByMonthResponse {
	return v.value
}

func (v *NullableTotalByMonthResponse) Set(val *TotalByMonthResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTotalByMonthResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTotalByMonthResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTotalByMonthResponse(val *TotalByMonthResponse) *NullableTotalByMonthResponse {
	return &NullableTotalByMonthResponse{value: val, isSet: true}
}

func (v NullableTotalByMonthResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTotalByMonthResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
